web page mobile version completed
AdrianScharff/My-portfolio-setup pull request #2
Opened 2023-06-02 20:32 UTC by AdrianScharff

Add sections "works" and "About" in html
Add all the images required for the project in html
Add the styling as in the template in css
Use grid in the works section and flexbox in each of the sections inside
Use flexbox in the About section

2023-06-02 22:22 UTC, Kossi-stack requested changes
## Hi @AdrianScharff,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ Linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-02 22:22 UTC, Kossi-stack commented on index.html
> +            <h1>Tonic</h1>
- [x] Kindly use another heading like h2 ...... hx for subtitles. Use h1 only for the main Title.

2023-06-02 22:22 UTC, Kossi-stack commented on index.html
> +            <h1>Multi-Post Stories</h1>
- [x] Kindly use another heading like h2 ...... hx for subtitles. Use h1 only for the main Title.

2023-06-02 22:22 UTC, Kossi-stack commented on index.html
> +            <h1>Tonic</h1>
- [x] Kindly use another heading like h2 ...... hx for subtitles. Use h1 only for the main Title.

2023-06-02 22:22 UTC, Kossi-stack commented on index.html
> +            <h1>Multi-Post Stories</h1>
- [x] Kindly use another heading like h2 ...... hx for subtitles. Use h1 only for the main Title.

2023-06-02 22:22 UTC, Kossi-stack commented on index.html
> +      <h1>About Myself</h1>
- [x] Kindly use another heading like h2 ...... hx for subtitles. Use h1 only for the main Title.

2023-06-02 22:22 UTC, Kossi-stack commented on index.html
> +     <div class="get">Get my resume</div>
- [ ] The button (e.g., "Get my resume") is a link `a` or `button` tag,
- Apart from being semantically correct, the `a` tag will let you connect to other sections of the website, using href.

2023-06-02 22:22 UTC, Kossi-stack commented on index.html
> +        <h1>Contact me</h1>
- [ ] Kindly use another heading like h2 ...... hx for subtitles. Use h1 only for the main Title.

2023-06-03 01:11 UTC, Efiamotu-1 approved these changes
Hi @AdrianScharff , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR Title & summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 04:37 UTC, merged